language: node_js
node_js:
  - 0.8
  - 0.6

before_script:
  - "export DISPLAY=:99.0"
  - "export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - testacular start test/testacular.conf.js --single-run --no-auto-watch --browsers PhantomJS
